package me.fang.kosh.exceptions

class ExitCalledException : RuntimeException()
